<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Feb 2023
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

# Objectives
- Understand the concept of **classes** and **objects**
- Explain the idea that _"everything in Python is an object"_
- Use the concept of an object's **property**
- Use the concept of an object's **method**

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

<img src='http://www.expertphp.in/images/articles/ArtImgC67UTd_classes_and_objects.jpg' width=75%/>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [1]:
class Pokemon:

    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: initalization arguments 
    - user specified inputs in initializing instance.
    - can have default arguments


#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [2]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

Let's check out some of the attributes

In [3]:
pikachu.attack_power

7

In [4]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [5]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [6]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [7]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [9]:
pikachu.evolve('Raichu')

In [10]:
pikachu.get_state()

{'name': 'Raichu', 'level': 3, 'life': 100, 'attack': 11, 'defense': 7}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.
- Koala takes in belly_weight, name, status(defalut is "Alive)
- alive_status method that if weight > 6, status = "Dead", if not then pass. It also prints out status


In [26]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def __init__(self, belly_weight, name, status = 'Alive'):
        self.name = name
        self.weight = belly_weight
        self.status = status 
    
    
    def alive_status(self):
        if self.weight > 6:
            self.status = "Dead"
        else:
            pass
        return(f"Koala status is {self.status}.")
        
        
        
    # eat_eucalyptus() method     
    def eat_eucalyptus(self, num_bunches = 1):
        if self.status == 'Alive':
            self.weight += num_bunches
        else:
            print("Dead koalas dont eat")
        

    # poop() method
    def poop(self, poop_weight = 0.5):
        if self.status == 'Alive':
            self.weight -= poop_weight
        else:
            print("Dead koalas don't poop.")
    
    
    

In [27]:
koala1 = Koala(1, 'Randy')
koala1.eat_eucalyptus()

In [28]:
koala1.eat_eucalyptus(2)

In [29]:
koala1.alive_status()

'Koala status is Alive.'

In [30]:
koala1.poop()

In [31]:
koala1.weight

3.5


- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [32]:
class Standardizer:
    
    def __init__(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [33]:
import pandas as pd
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [34]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [35]:
sd = Standardizer()

In [36]:
sd.mean_series

In [37]:
sd.stdev_series

Fit the transformer.

In [38]:
sd.fit(X_train)

In [39]:
sd.mean_series

age         54.214876
chol       245.471074
thalach    150.033058
dtype: float64

In [40]:
sd.stdev_series

age         9.202387
chol       47.584225
thalach    23.747263
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [41]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
251 -1.218692  0.032131 -0.296163
241  0.519987  0.074162 -0.296163
280 -1.327360  1.461176 -1.054145
200 -1.110025 -1.018637  1.135581
288  0.302652  1.881483 -0.296163

In [42]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 251 to 74
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [43]:
X_train_standard.std()

age        1.0
chol       1.0
thalach    1.0
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [44]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
205 -0.240685  0.200254  0.461819
199  1.171992  0.053146  0.335489
94  -1.001357 -1.796206 -0.506713
150  1.280659 -0.367161 -0.506713
85   1.389327  6.694003  0.419709

In [45]:
X_test_standard.std()

age        0.938358
chol       1.396267
thalach    0.812849
dtype: float64

Scikit-learn transformers are instances of class objects.

In [46]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [47]:
sklearn_sd.mean_

array([ 54.21487603, 245.47107438, 150.03305785])

In [48]:
sklearn_sd.scale_

array([ 9.18335416, 47.48580899, 23.69814788])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [49]:
print(X_train_sklearn.mean(axis = 0))

[ 3.00953018e-16  2.64251431e-16 -2.42230478e-16]


In [50]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [51]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [52]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [53]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [54]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [55]:
clr.coeff

array([-0.00264164, -0.00067642,  0.00881048])

In [56]:
sklearn_lr.coef_

array([-0.00264164, -0.00067642,  0.00881048])


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [57]:
clr.predict(X_test).iloc[0:5]

205    0.633219
199    0.577182
94     0.513330
150    0.411859
85     0.375770
dtype: float64

In [58]:
sklearn_lr.predict(X_test)[0:5]

array([0.63321947, 0.57718165, 0.51332995, 0.41185879, 0.37576994])

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.

# Level Up: Variables

Python is dynamically typed, meaning you don't have to instruct it as to what type of object your variable is.  
A variable is a pointer to where an object is stored in memory.

In [59]:
x = 3
print(id(x))
print(hex(id(x)))

4354996640
0x10393f9a0


In [67]:
y = 3
print(id(y))
hex(id(y))

4354996640


'0x10393f9a0'

In [61]:
x is y

True

In [62]:
# this can have implications 

x_list = [1,2,3,4]
y_list = x_list

In [63]:
x_list.pop()
print(x_list)
print(y_list)

[1, 2, 3]
[1, 2, 3]


In [64]:
# when you use copy(), you create a shallow copy of the object

z_list = y_list.copy()

In [65]:
id(z_list)

140387541539072

In [66]:
id(y_list)

140387541744064

In [68]:
y_list.pop()
print(y_list)
print(z_list)

[1, 2]
[1, 2, 3]


In [69]:
a_list = [[1,2,3], [4,5,6]]
b_list = a_list.copy()
a_list[0][0] ='z'
b_list

[['z', 2, 3], [4, 5, 6]]

In [70]:
import copy

# deepcopy is needed for mutable objects

a_list = [[1,2,3], [4,5,6]]
b_list = copy.deepcopy(a_list)
a_list[0][0] ='z'
b_list

[[1, 2, 3], [4, 5, 6]]

For more details on this general feature of Python, see [here](https://jakevdp.github.io/WhirlwindTourOfPython/03-semantics-variables.html).
For more on shallow and deep copying, go [here](https://docs.python.org/3/library/copy.html#copy.deepcopy).

# Level Up: `*args` and `**kwargs`

There are times when we want to have more flexibility in how we pass parameters to our functions/methods.

There's a whole lot we can discuss on this (checkout the [argument](https://docs.python.org/3/glossary.html#term-argument) & [parameter](https://docs.python.org/3/glossary.html#term-parameter) documentation for more details), but specifically we'll briefly discuss using `*args` and `**kwargs` in our functions/methods

> **NOTE**
>
> `*args` and `**kwargs` can be used in methods (functions associated with classes & objects) or in plain functions

## `*` Operator: `*args`

The single-asterisk operator `*` can be used to unpack iterables.

In [78]:
def product(factor1, factor2):
    out = factor1 * factor2
    return out

But if I want the product of *three* numbers this function won't do:

```python
product(3, 5, 6)
```

A nice way around this problem is to use the `*` operator.

In [72]:
def product_better(*factors):
    out = 1
    for f in factors:
        out *= f
    return out

In [73]:
product_better(2)

2

In [74]:
product_better(2, 4)

8

In [75]:
product_better(2, 4, 8, 16, 32)

32768

We can also use this notation to unpack an iterable to a function and will use each value as a _positional parameter_.

In [76]:
my_list_of_numbers = [1,2,3,4,5]

print(*my_list_of_numbers)
product_better(*my_list_of_numbers)

1 2 3 4 5


120

In [77]:
# Works for other iterables too!

my_range = range(2,10,2)

print(*my_range)
product_better(*my_range)

2 4 6 8


384

## `**` Operator: `*kwargs`

The double-asterisk operator  `∗∗`  is used for _keyword arguments_, i.e. _named arguments_.


In [ ]:
def hello_to_the_office(**kwargs):
    hello_strs = []
    # Iterate through each item of kwargs (a dictionary!)
    for position_title, name in kwargs.items():
        # Note that the keys are going to be treated as a string
        hello_strs.append(f'Hi {name}, the {position_title.title()}!')
        
    print('\n'.join(hello_strs))

In [ ]:
hello_to_the_office(
    regional_manager='Michael',
    office_administrato='Pam',
    regional_co_manager='Jim',
    asssistant_to_the_regional_manager='Dwight'
)

Here's a more complicated function that also uses `**kwargs`

In [ ]:
def report(to_print=True, **kwargs):
    
    # Effectively, kwargs is a dictionary
    the_keys = ';'.join(kwargs.keys())
    the_values = kwargs.values()
    
    # Note the safe way of getting the values
    if kwargs.get('is_bot'):
        print('ROBOT ALERT!!')
    
    if to_print:
        print(f'''
            The Keys:
                {the_keys}
            The Values:
                {the_values}
        ''')
    else:
        return the_keys, the_values

In [ ]:
# Note that these arguments were never defined in the report() function
report(name='Fry', birth_year=1985)

In [ ]:
report(name='Bender', titanium_level=0.4, birth_year=2996, is_bot=True)

We can also use the `**` operator to unpack a dictionary to a function as _named parameters_.

In [ ]:
def named_parameter_function(param0, param1, default=10):
    return (param0, param1, default)

In [ ]:
my_params = {'param0':'Zero', 'param1':10000, 'default':False}

named_parameter_function(**my_params)